[package]
name = "cacroix"
version = "0.1.0"
authors = ["arata <arata04962@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vecmath = "1.0.0"
